import Head from 'next/head'
import Link from 'next/link'

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Next Static</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {posts.map((post) => (
          <Link href={`/posts/${post.id}`} key={post.id}>
          <div>
            <h2>{post.slug}</h2>
          </div>
          </Link>
        ))}
      </div>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://samplewp1dev.wpenginepowered.com/index.php?rest_route=/wp/v2/posts', { cache: "no-cache" })
  const posts = await res.json()

  return {
    props: {
      posts,
    },
  }
}
